# Generated by Django 4.2.3 on 2023-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_rating_alter_comments_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='_rating',
        ),
    ]
