# Generated by Django 4.2.3 on 2023-07-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_author__rating_remove_comments__rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
