# Generated by Django 4.2.3 on 2023-07-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_text_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='content',
        ),
    ]
